### ISSUE TITLE
Show Active/Inactive pill for workflow rules

### ISSUE THREAD

**Issue by DanBeerNebula** [pgonzaleznetwork/sfdc-soup#14]
When displaying workflow rules in the impact analysis - can you show if the workflow rule is active or not in a little pill much like you do with read/write on apex classes, etc...

Thanks

**Comment by pgonzaleznetwork** [comment]
Hey @DanBeerNebula , this is coming up in HappySoup 2.0 which comes out later this year. I'm not doing any new dev work on the old HappySoup so we'll have to wait a bit but it'll be there! There will also be pills to show what type of workflow it is (i.e create only, or update, etc).

**Comment by DanBeerNebula** [comment]
Hey @pgonzaleznetwork - I thought you might say it will be in 2.0!

The type of workflow is a great idea!

Thanks,

**Comment by pgonzaleznetwork** [comment]
No worries, thanks for reaching out!
