### ISSUE TITLE
Not finding report information

### ISSUE THREAD

**Issue by ChuckJonas** [pgonzaleznetwork/sfdc-soup#25]
As a test, I've created a basic Report with a filter and tried running this on the field as an entry point.  It finds the layouts (so I know it's working), but doesn't return any information about the report.  I've tried with both standard and custom fields and with and without `enhancedReportData` turned on.

Example code:
```js

  let customField = {
    name: "Opportunity.Foo__c",
    type: "CustomField",
    id: normaliseSforceID("00NO8000002nDNx"),
    options: {
      enhancedReportData: true,
    },
  };

  let soupApi = sfdcSoup(connection, customField);
  let usageResponse = await soupApi.getUsage();

```

**Comment by pgonzaleznetwork** [comment]
Unfortunately Salesforce removed reports from the `MetadataCompoentDependency` API. It's only available from the Bulk API, which happysoup does not use. I should remove that option to avoid misleading users...

**Comment by ChuckJonas** [comment]
I had a feeling that might be the case.  Thanks for the heads up that the bulk API will actually return this info. That gives me a solid path forward.
