### ISSUE TITLE
Add 'attribute' column on CSV/Excel output for pills for that metadata type

### ISSUE THREAD

**Issue by DanBeerNebula** [pgonzaleznetwork/sfdc-soup#7]
One thing I’ve noticed - is that the csv/excel output doesn’t include if the apex class read or writes to a field when searching on that metadata.

maybe an “attributes” column at the end that contains the list of pills for that metadata type?

**Comment by pgonzaleznetwork** [comment]
This will be available on the next release which is going live in about 2/3 months.
